<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_TOKO_MuiBottomNavigationAction-icon fa fa_641cfb</name>
   <tag></tag>
   <elementGuidId>a3e36297-d9cc-461a-a7e6-2c9811e0e99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer']/div[3]/div/div/button[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBottomNavigationAction-icon fa fa-list-ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;AppFooterContainer&quot;]/div[@class=&quot;WidgetHelperRoot&quot;]/div[@class=&quot;MuiBottomNavigation-root jss30&quot;]/button[@class=&quot;MuiButtonBase-root MuiBottomNavigationAction-root jss31&quot;]/span[@class=&quot;MuiBottomNavigationAction-wrapper&quot;]/i[@class=&quot;MuiBottomNavigationAction-icon fa fa-list-ul&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/div[3]/div/div/button[2]/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]/span/i</value>
   </webElementXpaths>
</WebElementEntity>
